# Generated by Django 5.2.1 on 2025-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
