# Generated by Django 5.2.1 on 2025-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_sitesettings_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planfeature',
            options={},
        ),
        migrations.AddField(
            model_name='planfeature',
            name='value',
            field=models.CharField(blank=True, help_text='Leave blank for boolean features', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='name',
            field=models.CharField(choices=[('max_messages', 'Max Messages Per Day'), ('max_requests', 'Max Connection Requests Per Day'), ('max_views', 'Max Profile Views Per Day'), ('can_view_phone', 'Can View Phone Number'), ('can_request_phone', 'Can Request Phone Number'), ('priority_support', 'Priority Support'), ('verified_badge', 'Verified Badge'), ('other', 'Other (description only)')], max_length=50),
        ),
    ]
