# Generated by Django 5.2.1 on 2025-12-15 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_promocode_promocodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount applied via promo code', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final payable amount after discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='plans.promocode'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Base plan price at time of payment', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='plans.premiumplan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.URLField(blank=True, help_text='Uploaded payment proof URL', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='UPI / Bank Transaction ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat'), ('percent', 'Percentage')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
