# Generated by Django 5.2.1 on 2025-12-23 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteadmin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorUserCreation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual_entry",
                        help_text="Entry source: manual_entry, csv_upload, api_import, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the user was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp"
                    ),
                ),
                (
                    "created_user",
                    models.OneToOneField(
                        help_text="User account created by the operator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by_operator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="Operator who performed the data entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operator Created User",
                "verbose_name_plural": "Operator Created Users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["operator"], name="siteadmin_o_operato_a0aec1_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="siteadmin_o_created_025670_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operator", "created_user"),
                        name="unique_operator_user_creation",
                    )
                ],
            },
        ),
    ]
