# Generated by Django 5.2.1 on 2025-12-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_user_terms_accepted_user_terms_accepted_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_operator",
            field=models.BooleanField(default=False),
        ),
    ]
