# Generated by Django 5.2.1 on 2026-01-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_user_is_operator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Never Married", "Never Married"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Awaiting Divorce", "Awaiting Divorce"),
                    ("Annulled", "Annulled"),
                    ("Widowed", "Widowed"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
